version: '3'
services:

  auth_redis:
    container_name: auth_redis
    build:
      context: .
      dockerfile: docker_config/redis/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - auth_redis_data:/data
    ports:
      - $REDIS_PORT

  auth_postgres:
    build:
      context: .
      dockerfile: docker_config/postgres/Dockerfile
    container_name: auth_postgres
    env_file:
      - .env
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    command: -p $POSTGRES_PORT

  auth_app:
    build:
      context: .
      dockerfile: docker_config/app/Dockerfile
    container_name: auth_app
    image: auth_app
    volumes:
      - ./src/app:/opt/auth/app
      - ./src/migrations:/opt/auth/migrations
    entrypoint: ["python3", "runserver.py"]
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - auth_redis
      - auth_postgres

  auth_grpc:
      build:
        context: .
        dockerfile: docker_config/grpc/Dockerfile
      container_name: auth_grpc
      volumes:
        - ./src/grpc_app:/opt/auth/grpc_app
      entrypoint: ["python3",  "grpc_app/server.py"]
      env_file:
        - .env
      ports:
        - 5005:5005
      depends_on:
        - auth_redis
        - auth_postgres
        - auth_app

  auth_jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: auth_jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  auth_redis_data:
  auth_postgres_data:

