"""reate_unique_constraints

Revision ID: 0002
Revises: 0001
Create Date: 2022-05-01 20:43:58.291928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permission', ['id'])
    op.create_unique_constraint(None, 'profile', ['id'])
    op.create_unique_constraint(None, 'profile_role', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'role_permission', ['id'])
    op.create_unique_constraint(None, 'session', ['id'])
    op.create_unique_constraint(None, 'social_auth', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'social_auth', type_='unique')
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_constraint(None, 'role_permission', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'profile_role', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    # ### end Alembic commands ###
