# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\")\n\x18ProfilePermissionRequest\x12\r\n\x05token\x18\x01 \x01(\t\"?\n\x19ProfilePermissionResponse\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\x12\r\n\x05roles\x18\x02 \x03(\t2c\n\x07Profile\x12X\n\rGetPermission\x12!.profile.ProfilePermissionRequest\x1a\".profile.ProfilePermissionResponse\"\x00\x62\x06proto3')



_PROFILEPERMISSIONREQUEST = DESCRIPTOR.message_types_by_name['ProfilePermissionRequest']
_PROFILEPERMISSIONRESPONSE = DESCRIPTOR.message_types_by_name['ProfilePermissionResponse']
ProfilePermissionRequest = _reflection.GeneratedProtocolMessageType('ProfilePermissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEPERMISSIONREQUEST,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:profile.ProfilePermissionRequest)
  })
_sym_db.RegisterMessage(ProfilePermissionRequest)

ProfilePermissionResponse = _reflection.GeneratedProtocolMessageType('ProfilePermissionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEPERMISSIONRESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:profile.ProfilePermissionResponse)
  })
_sym_db.RegisterMessage(ProfilePermissionResponse)

_PROFILE = DESCRIPTOR.services_by_name['Profile']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILEPERMISSIONREQUEST._serialized_start=26
  _PROFILEPERMISSIONREQUEST._serialized_end=67
  _PROFILEPERMISSIONRESPONSE._serialized_start=69
  _PROFILEPERMISSIONRESPONSE._serialized_end=132
  _PROFILE._serialized_start=134
  _PROFILE._serialized_end=233
# @@protoc_insertion_point(module_scope)
